name: flutter_login_shared_preferences
description: A new Flutter package project.
version: 1.0.1
homepage: https://github.com/Iconica-Development
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0
  flutter_login_interface:
    git:
      url: https://github.com/Iconica-Development/flutter_login_service.git
      path: packages/flutter_login_interface
      ref: 1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 6.0.0

flutter:
