name: flutter_login_firebase_mfa
description: A new Flutter package project.
version: 1.0.0
publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  flutter_login_interface:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
