name: flutter_login_firebase_mfa
description: A new Flutter package project.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  flutter_login_interface:
    git:
      url: https://github.com/Iconica-Development/flutter_login_service.git
      path: packages/flutter_login_interface
      ref: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
