// SPDX-FileCopyrightText: 2022 Iconica
//
// SPDX-License-Identifier: BSD-3-Clause

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDBA-MI_mXS5F5V-B4HnN1_FQdQTAKiEI',
    appId: '1:936056564897:web:8f91d1b2cdc16b60b994e0',
    messagingSenderId: '936056564897',
    projectId: 'ico-firebase-login-example',
    authDomain: 'ico-firebase-login-example.firebaseapp.com',
    storageBucket: 'ico-firebase-login-example.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc0PLW3HA5-2CrornM61aHFDgyPar39Sc',
    appId: '1:936056564897:android:5db99d2997cb1832b994e0',
    messagingSenderId: '936056564897',
    projectId: 'ico-firebase-login-example',
    storageBucket: 'ico-firebase-login-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmrq_Q5utIF9yFIZ44WgQpSPZEmTubPfc',
    appId: '1:936056564897:ios:d3e70087e84023e4b994e0',
    messagingSenderId: '936056564897',
    projectId: 'ico-firebase-login-example',
    storageBucket: 'ico-firebase-login-example.appspot.com',
    iosClientId:
        '936056564897-aummlidpi9q89ch66qcpck11phn69i88.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmrq_Q5utIF9yFIZ44WgQpSPZEmTubPfc',
    appId: '1:936056564897:ios:d3e70087e84023e4b994e0',
    messagingSenderId: '936056564897',
    projectId: 'ico-firebase-login-example',
    storageBucket: 'ico-firebase-login-example.appspot.com',
    iosClientId:
        '936056564897-aummlidpi9q89ch66qcpck11phn69i88.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );
}
