name: flutter_login_firebase
description: Firebase login service for Flutter
version: 3.0.0
publish_to: "none"

environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  flutter:
    sdk: flutter
  flutter_login_service:
    git:
      url: https://github.com/Iconica-Development/flutter_login_service
      path: packages/flutter_login_service
      ref: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 6.0.0

flutter:
